name: 🐞 Report a Bug
description: Provide product feedback to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see! If applicable, add screenshots to help explain the issue.
      value:
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      placeholder: A clear and concise description of what you expected to happen.
      value:
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How would you reproduce the bug?
      description: Include steps to reproduce the behavior
      placeholder: e.g., 1. Go to '...', 2. Click on '....',  3. Scroll down to '...', 4. See error. If applicable, add screenshots to explain the issue.
      value:
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Did this happen via Desktop and/or Smartphone?
      multiple: true
      options:
        - Desktop
        - Smartphone
    validations:
      required: false
  - type: input
    id: operating-system
    attributes:
      label: Operating System
      placeholder: e.g., Windows 10, iOS
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Microsoft Edge
        - Firefox
        - Chrome
        - Safari
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g., 22
    validations:
      required: false 
  - type: input
    id: device
    attributes:
      label: Device
      placeholder: e.g., iPhone 6
    validations:
      required: false 
  - type: dropdown
    id: role
    attributes:
      label: What is your current role?
      multiple: false
      options:
        - Student
        - Professional
        - Educator
  - type: dropdown
    id: tech-topic
    attributes:
      label: What technical topic is this bug related to?
      multiple: true
      options:
        - AI/Data Science/Machine Learning
        - Application Development
        - Developer Tools
        - Low Code/Fusion Development
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell