apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: minecraft
spec:
  replicas: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: CONTAINER_REGISTRY_NAME.azurecr.io/minecraft-server:latest
        ports:
        - protocol: UDP
          containerPort: 19132
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-lb
spec:
  type: LoadBalancer
  ports:
  - port: 19132
    protocol: UDP
  selector:
    app: minecraft